import type { Task, Expense, PantryItem, User } from "./types";

export const users: User[] = [
  {
    id: "1",
    name: "Sam Wheeler",
    email: "sam@example.com",
    avatar: "/sam-wheeler.jpg",
  },
  {
    id: "2",
    name: "João Félix",
    email: "joao@example.com",
    avatar: "/joao-felix.jpg",
  },
  {
    id: "3",
    name: "Marcos Salgado",
    email: "marcos@example.com",
    avatar: "/marcos-salgado.jpg",
  },
  {
    id: "4",
    name: "Joana Maria",
    email: "joana@example.com",
    avatar: "/joana-maria.jpg",
  },
];

export const tasks: Task[] = [
  {
    id: "1",
    title: "Clean the Kitchen",
    assignee: "João Félix",
    assigneeAvatar: "/joao-felix.jpg",
    status: "todo",
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "2",
    title: "Grocery Shopping",
    assignee: "Marcos Salgado",
    assigneeAvatar: "/marcos-salgado.jpg",
    status: "todo",
    createdAt: new Date("2025-01-16"),
  },
  {
    id: "3",
    title: "Clean the bathroom",
    assignee: "Marcos Salgado",
    assigneeAvatar: "/marcos-salgado.jpg",
    status: "doing",
    createdAt: new Date("2025-01-14"),
  },
  {
    id: "4",
    title: "Wash the dishes",
    assignee: "Marcos Salgado",
    assigneeAvatar: "/marcos-salgado.jpg",
    status: "done",
    createdAt: new Date("2025-01-13"),
  },
  {
    id: "5",
    title: "Take out the trash",
    assignee: "Joana Maria",
    assigneeAvatar: "/joana-maria.jpg",
    status: "done",
    createdAt: new Date("2025-01-12"),
  },
  {
    id: "6",
    title: "Clean the Living Room",
    assignee: "Joana Maria",
    assigneeAvatar: "/joana-maria.jpg",
    status: "done",
    createdAt: new Date("2025-01-11"),
  },
];

export const expenses: Expense[] = [
  {
    id: "1",
    title: "Groceries - Weekly Shopping",
    amount: 45.5,
    category: "Groceries",
    paidBy: "João Félix",
    paidByAvatar: "/joao-felix.jpg",
    date: new Date("2025-01-20"),
    splitWith: ["1", "2", "3", "4"],
  },
  {
    id: "2",
    title: "Electricity Bill",
    amount: 32.0,
    category: "Utilities",
    paidBy: "Joana Maria",
    paidByAvatar: "/joana-maria.jpg",
    date: new Date("2025-01-18"),
    splitWith: ["1", "2", "3", "4"],
  },
  {
    id: "3",
    title: "Internet Bill",
    amount: 20.0,
    category: "Utilities",
    paidBy: "Marcos Salgado",
    paidByAvatar: "/marcos-salgado.jpg",
    date: new Date("2025-01-15"),
    splitWith: ["1", "2", "3", "4"],
  },
  {
    id: "4",
    title: "Cleaning Supplies",
    amount: 15.5,
    category: "Household",
    paidBy: "Sam Wheeler",
    paidByAvatar: "/sam-wheeler.jpg",
    date: new Date("2025-01-14"),
    splitWith: ["1", "2", "3", "4"],
  },
  {
    id: "5",
    title: "Pizza Night",
    amount: 28.0,
    category: "Food",
    paidBy: "João Félix",
    paidByAvatar: "/joao-felix.jpg",
    date: new Date("2025-01-12"),
    splitWith: ["1", "2", "3"],
  },
  {
    id: "6",
    title: "Toilet Paper & Tissues",
    amount: 12.0,
    category: "Household",
    paidBy: "Joana Maria",
    paidByAvatar: "/joana-maria.jpg",
    date: new Date("2025-01-10"),
    splitWith: ["1", "2", "3", "4"],
  },
];

export const pantryItems: PantryItem[] = [
  {
    id: "1",
    name: "Milk",
    quantity: 2,
    unit: "L",
    category: "Dairy",
    addedBy: "João Félix",
    addedByAvatar: "/joao-felix.jpg",
    expiryDate: new Date("2025-01-25"),
    lowStock: false,
  },
  {
    id: "2",
    name: "Eggs",
    quantity: 6,
    unit: "units",
    category: "Dairy",
    addedBy: "Marcos Salgado",
    addedByAvatar: "/marcos-salgado.jpg",
    expiryDate: new Date("2025-01-28"),
    lowStock: true,
  },
  {
    id: "3",
    name: "Bread",
    quantity: 1,
    unit: "loaf",
    category: "Bakery",
    addedBy: "Joana Maria",
    addedByAvatar: "/joana-maria.jpg",
    expiryDate: new Date("2025-01-23"),
    lowStock: true,
  },
  {
    id: "4",
    name: "Rice",
    quantity: 5,
    unit: "kg",
    category: "Grains",
    addedBy: "Sam Wheeler",
    addedByAvatar: "/sam-wheeler.jpg",
    lowStock: false,
  },
  {
    id: "5",
    name: "Pasta",
    quantity: 3,
    unit: "kg",
    category: "Grains",
    addedBy: "João Félix",
    addedByAvatar: "/joao-felix.jpg",
    lowStock: false,
  },
  {
    id: "6",
    name: "Tomato Sauce",
    quantity: 2,
    unit: "jars",
    category: "Canned",
    addedBy: "Marcos Salgado",
    addedByAvatar: "/marcos-salgado.jpg",
    lowStock: true,
  },
  {
    id: "7",
    name: "Olive Oil",
    quantity: 1,
    unit: "bottle",
    category: "Oils",
    addedBy: "Joana Maria",
    addedByAvatar: "/joana-maria.jpg",
    lowStock: false,
  },
  {
    id: "8",
    name: "Coffee",
    quantity: 500,
    unit: "g",
    category: "Beverages",
    addedBy: "Sam Wheeler",
    addedByAvatar: "/sam-wheeler.jpg",
    lowStock: true,
  },
];
